### ISSUE TITLE
[P2][Installs]Update for 'Install PostgreSQL using WSL'

### ISSUE THREAD

**Issue by OpenWaygate** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#15]
In section **Install**, line 3,
For ubuntu 18.04, it should be
`deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main`
for 16.04, is
`deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main`
for 14.04, is
`deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main`

[reference](https://www.postgresql.org/download/linux/ubuntu/)

**Comment by michaeltreat** [comment]
Thank you, that's perfect! Please feel free to make a PR if you like and I will review and accept it. If not I can get to it during the next update round as well. Thanks again!

**Comment by michaeltreat** [comment]
Thank you again.

Here is a link to the page in question. If someone can make an appropriate PR and link this bug in and close it that would be awesome.

https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/blob/master/readmes/installs/PostgreSQL.md

**Comment by michaeltreat** [comment]
Added Tags to Title.
