### ISSUE TITLE
Re-open WSL after Updating its Profile

### ISSUE THREAD

**Issue by Alferguson** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#19]
In 04_updating_terminal.md after step 5 of saving the changes made to profile, there should be a step that tells the user to close and open the WSL terminal to see their changes. If one does not reopen their WSL, the cdwr command does not work.

Note, I have not tested this out on other machines and only have done it once. Thank you.

**Comment by michaeltreat** [comment]
This seems like something we should recommend new users to do, otherwise it might lead to more confusion, and it is likely a best practice anyway. Thanks for supporting this!
