### ISSUE TITLE
[P1][01_preface.md][Typos][Content] Content enhancements and Questions.typo on the 01_preface.md page 

### ISSUE THREAD

**Issue by NedRagdnuos** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#21]
Hi Michael,

There's a typo on the 01_preface.md page (extra word "to"):
 
  There have been many different workarounds for to this problem

should be:

  There have been many different workarounds for this problem

Thanks for putting together the article. This WSL is very useful.
It's great for running the "lftp" program, to speed up downloads
from remote servers by using multiple connections, e.g.

lftp -c "mirror --use-pget-n=4 --verbose sftp://username:passwword@hostname/pathname"

Cheers,
Ned.

**Comment by NedRagdnuos** [comment]
Another couple of typos:

-------------------------------------------------------------
in it's POSIX environment

should be:

in its POSIX environment

"Its" is the possessive form of "it". 

-------------------------------------------------------------
so it cannot run any programs that need one, IE: Browser

should be:

so it cannot run any programs that need one, i.e.: Browser

("IE" might be confused with "Internet Explorer")

-------------------------------------------------------------

it can use them with it's software just fine as well

should be:

it can use them with its software just fine as well

-------------------------------------------------------------

termianl  -> terminal

-------------------------------------------------------------

On the 02_WSL_Ubuntu_setup.md page:

and talks about work-flow in general. They are much more concise than the over-view doc.

should be:

and talks about workflow in general. They are much more concise than the overview doc.

-------------------------------------------------------------
I'm not sure "Window's" would be the right way to indicate the possessive here. Also, could you explain in what sense this "user" has any independent existence from your Windows User? I mean, don't you have to be already logged in as your Windows User to even launch the WSL terminal? My impression was that this password was mainly intended to be used as the "sudo" password, i.e. the root password used to add software and perform any administrative actions within the WSL environment.

Essentially all of your Window's files can be viewed and modified by this user, so keep that password safe and strong.

Perhaps:

Essentially all of the files within your Microsoft Windows filesystem can be viewed and modified by this user, so keep that password safe and strong.

----------------------------------------------------------------------------------------

premissions  -> permissions

On the topic of permissions, in the Ubuntu WSL from the Microsoft Store,
I found that to run GNU screen ("sudo apt-get install screen") I ended up 
needing to create /run/screen and give it permissions "chmod 777 /run/screen",
which I have never needed to do on regular Ubuntu.

----------------------------------------------------------------------------------------

Perhaps rewrite the following (to avoid confusion with the concept of "root" user):

This is the root level of your Ubuntu user.

as:

This is the top level of the home directory of your Ubuntu user.

----------------------------------------------------------------------------------------

You will need to run a quick couple commands in order to run updates software updater. 

should be:

You will need to run a quick couple commands in order to run software updates and install new software packages. 

(unless you've done "apt-get update", the "apt-cache search" command won't find the package name that you're seeking, e.g. "apt-cache search openconnect" doesn't find it unless you first do the "apt-get update" -- by the way, it might be nice to implement the /dev/tun tunnel device, so that openconnect and other similar networking and VPN tools could be used within WSL).

---------------------------------------------------

Eventually, as this grow, we hope to include exploring multi-distro installations

typo on "grow":

Eventually, as this grows, we hope to include exploring multi-distro installations

---------------------------------------------------

On the topic of "functional feedback about how the WSL app works", 
I was curious why the "Properties" checkbox needs "Shift"?

  [x] Use Ctrl+Shift+C/V as Copy/Paste

Wouldn't it have been more similar to other POSIX operating systems
to allow regular Ctrl C and Ctrl V without needing to hold down
the Shift key too? Could checkboxed like this be added to "Properties"?

  [x] Use Ctrl+C/V as Copy/Paste
  [x] Use middle-click to paste

Allowing middle-click to paste would go a very long way toward making
the WSL terminal window "feel more like home", in the sense that it would
feel more similar to a regular "xterm". Even though I realize that the goal of
WSL isn't to offer a GUI, all many developers on POSIX systems don't really 
use a GUI for anything other than keeping multiple terminal windows open on 
their workstation at the same time (with many of these terminal windows 
running GNU screen sessions logged in to hundreds of different servers).
 
Also, it would be helpful to have a way to specify the initial number of
columns and rows (e.g. an option to create a terminal window with
24 rows, 80 columns similar to the default for many POSIX terminals
would be useful, as well as perhaps an option to create a terminal of 
the maximum vertical size while still having 80 columns). These kinds
of terminal are often used by POSIX developers when coding to ensure
that their code doesn't go off the edge of the page when printed out 
later on, and also to help in code review tools which often get their
line numbering messed up when too many columns are used in the
file being reviewed.

--------------------------------------------------------------------

On the page "04_updating_terminal.md" it seems strange to use "sudo"
to create or edit the $HOME/.profile file. I didn't need to use "sudo" for 
this on my April 21 2019 WFL installation of Ubuntu on Windows 10,
and I don't think it'd be needed on any of the POSIX systems I've used.

sudo touch .profile
sudo nano .profile

--------------------------------------------------------------------

**Comment by michaeltreat** [comment]
Thanks for this! I've  just now had a chance to read through it. I will take a deeper look at this over the next two weeks and try to answer as many of these items as I can. 

Since you still have context here would you be able to make PR that we can look over: 

Yes on all the typos, and the password change looks good too, but I'll need to take a longer look at the rest. I also probably overuse sudo which is why you'll see it used incorrectly. If you understand how to use sudo well then please update those sections too.

 Also, my knowledge about Linux and Windows isn't that deep yet and I may not be the best person to answer some of these questions, so I open them to the community to answer as well. If you are confident that you know the topic, please add it in the PR as well. 

Thanks again for taking the time to look into this at that level! Let me know if you need anything or if there is anything I can do to help you.

**Comment by michaeltreat** [comment]
Updating the title: 

Before:

**typo on the 01_preface.md page **

After:

[P1][01_preface.md][Typos][Content] Content enhancements and Questions.


Is that an appropriate title?
