### ISSUE TITLE
Use Git installed in WSL(Windows Subsystem for Linux) from Windows and Visual Studio Code

### ISSUE THREAD

**Issue by Dev-rick** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#23]
First, thanks for this great tutorial. It helped me a lot!

I found this interesting guide for avoiding installing git on windows and still be able to use it on windows but not sure if it is a good idea. What do you think?

https://github.com/hangxingliu/wslgit

**Comment by DelfCo** [comment]
Recent updates to [VSCode and the Remote - WSL extension](https://code.visualstudio.com/docs/remote/wsl) appear to offer the same functionality, direct from Microsoft.
