### ISSUE TITLE
Updating Terminal

### ISSUE THREAD

**Issue by SherylHohman** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#24]
I'm running into an issue after updating `.profile`.
I replace the default profile code with the code you provide.
Then I close the terminal. Then restart Ubuntu.

When I do so, the terminal hangs. There is never any prompt.
CPU usage quickly skyrockets to 100%. - Mostly Git.
Closing the terminal, returns CPU back to normal.

I've uninstalled, re-installed Ubuntu (WSL) few times ( in case I caused a typo that broke the `.profile` file ).
I've double checked the .profile code.

Each time, after updating Terminal's look, Ubuntu essentially breaks.
The terminal is unresponsive upon open.
CPU (via git) immediately shoots up to 100%.

Any hints ideas ?
I'm using the latest version of Windows 10.

**Comment by michaeltreat** [comment]
Sorry for the delay in getting back. Are you still having this issue? Can you paste the code you are putting into the ``` .profile ``` file here as well? I'll take a look at it to make sure nothing is missing or added. 

Thanks
