### ISSUE TITLE
Installing Android studio on WSL/WSL2

### ISSUE THREAD

**Issue by mwoodpatrick** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#26]
Is it possible to install Android studio and have it work reliably on WSL/WSL2 if so what is the procedure

**Comment by dabwitso** [comment]
I managed to install after days of searching for a solution. Here is the link to first install xfce4 and enable display via windows 10: https://autoize.com/xfce4-desktop-environment-and-x-server-for-ubuntu-on-wsl-2/

Afterwards, you can install android studio by downloading it from official site and running it in your wsl2 environment.

**Comment by Ramesh-X** [comment]
@dabwitso The link you provided is not working for me

**Comment by amalmohann** [comment]
![image](https://user-images.githubusercontent.com/15846660/111740673-2830bd00-88ab-11eb-9dfe-2cf0dd639a6c.png)

link is not working

**Comment by michaeltreat** [comment]
Linking to a possible solution that seems to work.
https://gist.github.com/steveclarke/d988d89e8cdf51a8a5766d69ecb07e7b
