### ISSUE TITLE
Open Source Call!

### ISSUE THREAD

**Issue by michaeltreat** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#3]
**This guide's mission is to make WSL accessible to new and experienced developers alike, in a fast and in-depth format.**

This is an open invitation to everyone to create issues, correct mistakes and misinformation, and to contribute in any way they can to help improve this guide!

Personally, as both a new dev and an experienced dev, I have found it frustrating when reading a guide or article that doesn't go in-depth on the topic that it is covering. If I want to learn about something (and I'm not reading the docs ) I want to know the how's AND the why's of everything. I find it a better use of my time to read something that is written in an in-depth format from the start as it is structured in such a way as to cover everything from end-to-end, and I don't have to piece together many different articles to get a full picture.

On the other hand, the short, to-the-point guides are also incredibly useful for when I just want to get something done. That is why I have tried to write this guide in such a way that a developer of any skill can come in and find exactly what they need. 

So, these are the guidelines I am keeping in mind when writing this guide:

- Assume the person reading the guide has no idea about the topic. Include everything you think they should know.
- Keep the beginning dev in mind at all times. _Everyone_ is a beginner. Some just have more practice at it.
- Be thorough.  Whenever possible explain how AND why. If you don't know both, then look it up, or make it clear you don't know the why.
- Include use-cases. Use analogies and scenarios to explain concepts. Knowledge vs wisdom. Knowing how vs knowing when.

If you would like to contribute then please try to follow these guidelines so we can keep this guide consistent and accessible to everyone!

**Comment by repoman-git** [comment]
Hello Michael, Many thanks for taking the time to prepare this file.  I am new to WSL and linux in general; I'm working ,my way through some AWs courses and thought I'd also try an grapple with Linux.....your doc was really great, for me, at least.

**Comment by jaredpattison** [comment]
Hi Michael, great guide. One small issue I had was that the cdwr alias did not take effect until I opened a new shell, rookie mistake but noting may save others the confusion I experienced. 

Thanks,

**Comment by michaeltreat** [comment]
Thanks for the compliments @repoXman !

And thanks for the feedback @jaredpattison . Please feel free to update that section to make that more clear and make a PR! 

Thank you!

**Comment by Alferguson** [comment]
Hi Michael, I just submitted that as an issue so I'll make an update to that section in a PR.

**Comment by michaeltreat** [comment]
> Hi Michael, I just submitted that as an issue so I'll make an update to that section in a PR.

https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/pull/20

Thanks for your PR @Alferguson
