### ISSUE TITLE
WSL2 update?

### ISSUE THREAD

**Issue by Meryama03** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#31]
Any new version of this documentation coming soon? targeting WL2?

**Comment by zeyad-kay** [comment]
Just follow the instructions in the mongodb installation manual for linux: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
But when trying to run the service, it won't work so you will have to manually create the service. So follow the instructions in this comment:  https://github.com/microsoft/WSL/issues/796#issuecomment-611626709

**Comment by divyanshu013** [comment]
I followed the [guide from Microsoft](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2) and updated to WSL2 without any trouble. Perhaps this can be mentioned in the guide @michaeltreat ?

**Comment by michaeltreat** [comment]
Hi, sorry for the delay. @divyanshu013 I updated the guide to point to the WSL docs, which also includes instructions on how to upgrade to WSL 2.

 @Meryama03 I won't be updating this doc to target WSL 2 specifically, but I added another sub-section to the install section that points people to the MSFT docs for WSL 2. Most of this doc works the same with WSL 2 as it does with WSL 1.
