### ISSUE TITLE
No Dirmngr

### ISSUE THREAD

**Issue by EduardoCerutti** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#34]
I tried to run the second step of the installation tutorial but it ended with the following error.

`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5`
`Executing: /tmp/apt-key-gpghome.voA0lZRTwz/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5`
`gpg: connecting dirmngr at '/tmp/apt-key-gpghome.voA0lZRTwz/S.dirmngr' failed: IPC connect call failed`
`gpg: keyserver receive failed: No dirmngr`

**Comment by michaeltreat** [comment]
@TCsTheMechanic were you able to get this solved?
