### ISSUE TITLE
Screencast Blurry

### ISSUE THREAD

**Issue by brettation** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#5]
Kudos Mike on helping folks get WSL setup. I think that is great that you both provide shortcuts and long form context.   I just wanted to give you a heads up... it looks like there are some sections of your Explainer Videos that are coming across as Blurry.   For example in your third WSL Video -- you have a blurry section  that spans from approx. Timecode: 29:17-31:07.    

I know you were trying to present the whole thing from A-Z (real-world, real-time) ... which is also really helpful to folks learning.  However, in this context, instead of doing the whole shebang over again... maybe you can just splice in the corrected Vid section ala this is what I am/was doing on the Command Line, etc.   Again, thank you for helping others.
![help_michael_treat_wsl_vid_issue_blurry](https://user-images.githubusercontent.com/423872/48314394-05819180-e597-11e8-839f-201d86a7cdd1.png)

**Comment by michaeltreat** [comment]
Thanks for the feedback and the compliments! 

My video editing skills are pretty minimal but I am up for the challenge. I will have some free time over the next month and will work on getting this updated.

**Comment by brettation** [comment]
Mike your Vid may be fine after all.  Sorry if this turns out to be a false alarm.

If you are NOT able to reproduce issue, I suspect there may be some bandwidth snag, causing the blur going on on my end.

**Comment by brettation** [comment]
Yep, bandwidth issue on my end.
