### ISSUE TITLE
Set the Git Config

### ISSUE THREAD

**Issue by thdoan** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#6]
Hi, the [Set the Git Config](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/blob/master/readmes/05_VSCode_Node_GIt_install.md#set-the-git-config) section is a bit ambiguous: should we enter the commands in the VSCode terminal, the Ubuntu terminal, or both?

**Comment by michaeltreat** [comment]
The short answer is any terminal. I am working on clarifying this in the next update. With the two file systems, you will likely have Git installed on both file systems, but the `-g` flag typically refers to the Git installed on the Ubuntu FS. When you move to the Windows FS and use Git it is the Windows version, unless you use the -g flag. 

A quick fix for this right now is to open any terminal and type in those commands. No matter which one you use it should work. In a later update I will go deeper into using Git with both file systems as well as best practices.

**Comment by thdoan** [comment]
Thanks, Michael. I entered the command in both terminals :-).
